[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin-contracts/contracts=lib/openzeppelin-community-contracts/contracts",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
